platform :ios, '9.0'
inhibit_all_warnings!

target 'SPFileManagerExample' do
  use_frameworks!

  # Pods for SPFileManagerExample
pod 'SPFileManager', :path => '../'

  target 'SPFileManagerExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
